name: RNAseq_kallisto
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - bbmap=38.57
  - fastp=0.20.0
  - fastqc=0.11.8
  - gxx_linux-64
  - kallisto=0.46.0
  - conda-forge::libiconv=1.16
  - multiqc=1.7
  - python=3.7.3
  - r-base=3.6.1
  - r-devtools
  - r-msigdbr
  - r-venndiagram
  - r-dplyr
  - r-ggplot2
  - r-gridextra
  - r-magrittr
  - r-matrixStats
  - r-readr
  - r-remotes
  - r-sleuth
  - r-tibble
  - r-tidyr
  - bioconductor-biobase
  - bioconductor-deseq2
  - bioconductor-biomart
  - bioconductor-edger
  - bioconductor-fgsea
  - bioconductor-limma
  - bioconductor-rhdf5
